# Header
menu:
  Home: /
  Archives: /archives
  About me: /about
  English blog: 'https://en.ikazoy.me'
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png