# Header
menu:
  Home:
    path: /
  Archives:
    path: /archives
  About me:
    path: /about
  English blog:
    open_new_tab: true
    path: 'https://en.ikazoy.me'
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-129123080-1
favicon: /favicon.png